Repository DNNCommunity/dnn-elements, pull requests merged in 2022-11, with the labels that each got.

#645 Some revisions to dnn-monaco-editor
  custom-elements.json
  licenses.txt
  src/components.d.ts
  src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  src/components/dnn-monaco-editor/readme.md
  src/components/dnn-monaco-editor/types/options.ts
Labels: enhancement

#647 Simplifies monaco editor instanciation
  licenses.txt
  src/components.d.ts
  src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  src/index.html
Labels: enhancement

#646 Resolve absolute module path issues with license checker
  custom-elements.json
  licenses.json
  licenses.txt
  package-lock.json
  package.json
Labels: bug

#644 Implement monaco editor
  .gitignore
  custom-elements.json
  licenses.json
  package-lock.json
  package.json
  src/components.d.ts
  src/components/dnn-monaco-editor/dnn-monaco-editor.scss
  src/components/dnn-monaco-editor/dnn-monaco-editor.stories.ts
  src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  src/components/dnn-monaco-editor/readme.md
  src/components/dnn-monaco-editor/utils/code.utils.ts
  src/index.html
Labels: feature
