Repository DNNCommunity/dnn-elements, pull requests merged in 2022-02, with the labels that each got.

#445 Replaced all Eraware references for DnnCommunity
  .github/workflows/Deploy.yml
  README.md
  _build/Build.cs
  licenses.txt
  package-lock.json
  package.json
Labels: documentation

#446 Fixed casing for organization name
  _build/Build.cs
Labels: bug

#447 Released v0.13.0
  .github/workflows/Deploy.yml
  README.md
  _build/Build.cs
  licenses.txt
  package-lock.json
  package.json
Labels: build

#448 Fixed a versioning issue on NPM
  _build/Build.cs
Labels: build

#450 Released v0.13.1
  _build/Build.cs
Labels: build

#449 Updated link to docs site
  README.md
Labels: documentation

#451 Another missed eraware reference
  README.md
Labels: documentation

#452 implemented dnn-vertical-splitview component
  licenses.txt
  src/components.d.ts
  src/components/dnn-image-cropper/dnn-image-cropper.tsx
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
  src/components/dnn-vertical-splitview/readme.md
  src/index.html
  src/utilities/mouseUtilities.ts
Labels: enhancement

#453 Resolved multiple warnings about changing state during render
  licenses.txt
  src/components/dnn-image-cropper/dnn-image-cropper.tsx
  src/components/dnn-tabs/dnn-tabs.tsx
  src/components/dnn-treeview-item/dnn-treeview-item.tsx
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
Labels: enhancement

#454 Created a vertical-overflow-menu component
  src/components.d.ts
  src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.scss
  src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.tsx
  src/components/dnn-vertical-overflow-menu/readme.md
  src/index.html
Labels: enhancement

#456 Changed how to style the pane colors
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
  src/components/dnn-vertical-splitview/readme.md
  src/index.html
Labels: bug

#457 Removed left pane 100% height
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
Labels: bug

#460 Build es5 components for production
  stencil.config.ts
Labels: enhancement

#459 Fixed multiple style issues with overflow-menu
  src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.scss
  src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.tsx
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
  src/index.html
Labels: bug

#461 Fixed some more style issues with splitter
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
  src/index.html
Labels: bug

#462 Added events to treeview expander
  src/components.d.ts
  src/components/dnn-treeview-item/dnn-treeview-item.scss
  src/components/dnn-treeview-item/dnn-treeview-item.tsx
  src/components/dnn-treeview-item/readme.md
  src/index.html
Labels: enhancement

#463 Resolved collapsible nesting issues
  src/components/dnn-collapsible/dnn-collapsible.scss
  src/components/dnn-collapsible/dnn-collapsible.tsx
  src/index.html
Labels: bug

#466 Resolve height issue with treeview first child
  package-lock.json
  src/components/dnn-treeview-item/dnn-treeview-item.scss
Labels: enhancement

#467 Add watch for expanded prop and handle accordingly
  src/components.d.ts
  src/components/dnn-treeview-item/dnn-treeview-item.tsx
Labels: enhancement

#468 Resolve issue with initial expanded treeview item
  src/components/dnn-treeview-item/dnn-treeview-item.tsx
Labels: bug

#469 Resolve issue with animating collapse of item
  src/components/dnn-collapsible/dnn-collapsible.tsx
Labels: bug

#470 Merge latest 0.14.0 fixes back into develop
  package-lock.json
  src/components.d.ts
  src/components/dnn-collapsible/dnn-collapsible.scss
  src/components/dnn-collapsible/dnn-collapsible.tsx
  src/components/dnn-treeview-item/dnn-treeview-item.scss
  src/components/dnn-treeview-item/dnn-treeview-item.tsx
  src/components/dnn-treeview-item/readme.md
  src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.scss
  src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.tsx
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
  src/components/dnn-vertical-splitview/readme.md
  src/index.html
  stencil.config.ts
Labels: bug

#471 Released v0.14.0
  README.md
  licenses.txt
  package-lock.json
  src/components.d.ts
  src/components/dnn-collapsible/dnn-collapsible.scss
  src/components/dnn-collapsible/dnn-collapsible.tsx
  src/components/dnn-image-cropper/dnn-image-cropper.tsx
  src/components/dnn-tabs/dnn-tabs.tsx
  src/components/dnn-treeview-item/dnn-treeview-item.scss
  src/components/dnn-treeview-item/dnn-treeview-item.tsx
  src/components/dnn-treeview-item/readme.md
  src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.scss
  src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.tsx
  src/components/dnn-vertical-overflow-menu/readme.md
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
  src/components/dnn-vertical-splitview/readme.md
  src/index.html
  src/utilities/mouseUtilities.ts
  stencil.config.ts
Labels: build
