Repository DNNCommunity/dnn-elements, pull requests merged in 2022-03, with the labels that each got.

#479 Automated update to treeview-item readme
  src/components/dnn-treeview-item/readme.md
Labels: documentation

#483 Ensure splitview separator follows changes in element resize
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
Labels: bug

#484 Released v0.14.1
  package-lock.json
  package.json
  src/components/dnn-treeview-item/readme.md
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
Labels: build

#486 Initial implementation of Storybook with one component (dnn-button)
  .storybook/main.js
  .storybook/preview.js
  licenses.txt
  package-lock.json
  package.json
  src/components/dnn-button/dnn-button.stories.ts
Labels: enhancement

#488 Add Stencil auto-generated documentation within Storybook
  .storybook/main.js
  .storybook/preview.js
  .storybook/stories/automatedStories.js
  licenses.txt
  package-lock.json
  package.json
  src/components/dnn-button/dnn-button.stories.ts
  src/components/dnn-button/dnn-button.stories.tsx
  src/components/dnn-checkbox/dnn-checkbox.stories.tsx
  src/global.d.ts
Labels: enhancement

#490 Implement storybook and auto include Stencil docs
  .storybook/main.js
  .storybook/preview.js
  licenses.txt
  package-lock.json
  package.json
  src/components/dnn-button/dnn-button.stories.ts
  src/global.d.ts
Labels: documentation

#491 Created story for collapsible
  .storybook/main.js
  licenses.txt
  package-lock.json
  package.json
  src/components/dnn-collapsible/dnn-collapsible.stories.ts
  src/components/dnn-collapsible/dnn-collapsible.tsx
Labels: documentation

#492 Added accessibility validation in storybook
  .storybook/main.js
  licenses.txt
  package-lock.json
  package.json
Labels: documentation

#503 Storybook theme and features
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview-head.html
  .storybook/preview.js
  custom-elements.json
  licenses.txt
  package-lock.json
  package.json
  src/components/dnn-button/dnn-button.stories.ts
  src/components/dnn-button/dnn-button.tsx
  src/components/dnn-collapsible/dnn-collapsible.stories.ts
  stencil.config.ts
Labels: documentation

#504 Fixed an issue where storybook would get into an infinite loop
  .storybook/manager.js
  .storybook/preview-head.html
  .storybook/preview.js
  custom-elements.json
  package-lock.json
  package.json
Labels: enhancement

#520 Added story for dnn-chevron
  src/components/dnn-chevron/dnn-chevron.stories.ts
Labels: documentation

#521 Added story for dnn-color-picker
  src/components/dnn-color-picker/dnn-color-picker.stories.ts
Labels: documentation

#523 Bumped to Nuke6 Ubuntu build
  .github/dependabot.yml
  .github/workflows/Deploy.yml
  .github/workflows/PR_Validation.yml
  .github/workflows/Publish_Site.yml
  _build/Build.cs
  _build/_build.csproj
  build.cmd
  build.sh
  global.json
  licenses.txt
  package-lock.json
  package.json
  src/utilities/colorInfo.spec.ts
Labels: build

#519 Added story for `dnn-checkbox`
  src/components/dnn-checkbox/dnn-checkbox.stories.ts
Labels: documentation

#501 Added a permissions grid component
  custom-elements.json
  src/components.d.ts
  src/components/dnn-button/readme.md
  src/components/dnn-checkbox/dnn-checkbox.scss
  src/components/dnn-checkbox/dnn-checkbox.stories.ts
  src/components/dnn-checkbox/dnn-checkbox.tsx
  src/components/dnn-checkbox/readme.md
  src/components/dnn-collapsible/readme.md
  src/components/dnn-permissions-grid/dnn-permissions-grid.scss
  src/components/dnn-permissions-grid/dnn-permissions-grid.stories.ts
  src/components/dnn-permissions-grid/dnn-permissions-grid.tsx
  src/components/dnn-permissions-grid/localization-interface.tsx
  src/components/dnn-permissions-grid/permissions-interface.ts
  src/components/dnn-permissions-grid/readme.md
  src/components/dnn-permissions-grid/role-group-interface.ts
  src/components/dnn-permissions-grid/role-interface.ts
  src/components/dnn-permissions-grid/searched-user-interface.ts
  src/components/dnn-searchbox/dnn-searchbox.tsx
  src/components/dnn-searchbox/readme.md
  src/index.html
Labels: breaking

#522 Added story for dnn-dropzone
  src/components/dnn-dropzone/dnn-dropzone.stories.ts
Labels: documentation

#524 Add story for dnn-image-cropper
  src/components/dnn-image-cropper/dnn-image-cropper.stories.ts
Labels: documentation

#525 Added story for `dnn-searchbox`
  src/components/dnn-searchbox/dnn-searchbox.stories.ts
Labels: documentation

#526 Add story for dnn-modal and update component to add visible prop
  src/components.d.ts
  src/components/dnn-modal/dnn-modal.stories.ts
  src/components/dnn-modal/dnn-modal.tsx
Labels: documentation, enhancement

#527 Add story for `dnn-tab`
  src/components/dnn-chevron/dnn-chevron.stories.ts
  src/components/dnn-tab/dnn-tab.stories.ts
Labels: documentation

#529 Created story for dnn-sort-icon
  .storybook/utilities.ts
  src/components/dnn-sort-icon/dnn-sort-icon.scss
  src/components/dnn-sort-icon/dnn-sort-icon.stories.ts
Labels: documentation

#531 Add story for dnn-toggle and resolve a CSS var issue with component
  src/components/dnn-toggle/dnn-toggle.scss
  src/components/dnn-toggle/dnn-toggle.stories.ts
Labels: bug, documentation

#530 Fixed multiple missing components declaration in stories
  custom-elements.json
  src/components.d.ts
  src/components/dnn-checkbox/readme.md
  src/components/dnn-collapsible/dnn-collapsible.stories.ts
  src/components/dnn-collapsible/dnn-collapsible.tsx
  src/components/dnn-collapsible/readme.md
  src/components/dnn-dropzone/readme.md
  src/components/dnn-modal/readme.md
  src/components/dnn-permissions-grid/dnn-permissions-grid.stories.ts
  src/components/dnn-searchbox/dnn-searchbox.stories.ts
  src/components/dnn-sort-icon/readme.md
  src/components/dnn-tabs/readme.md
  src/components/dnn-toggle/readme.md
  src/components/dnn-vertical-splitview/readme.md
Labels: documentation

#528 Add story for `dnn-tabs-story`
  src/components/dnn-tabs/dnn-tabs.stories.ts
Labels: documentation

#532 Commits new docs
  custom-elements.json
  src/components/dnn-checkbox/readme.md
  src/components/dnn-dropzone/readme.md
  src/components/dnn-modal/readme.md
  src/components/dnn-sort-icon/readme.md
  src/components/dnn-tabs/readme.md
  src/components/dnn-toggle/readme.md
  src/components/dnn-vertical-splitview/readme.md
Labels: documentation

#534 Add story for `dnn-vertical-splitview` and resolve CSS var docs issue
  custom-elements.json
  licenses.txt
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.stories.ts
Labels: bug, documentation

#533 Added story to dnn-treeview-item
  src/components/dnn-treeview-item/dnn-treeview-item.stories.ts
  src/components/dnn-treeview-item/dnn-treeview-item.tsx
  src/components/dnn-treeview-item/readme.md
Labels: documentation

#535 Adjusted the build to publish the storybook
  .gitignore
  _build/Build.cs
  custom-elements.json
  licenses.txt
  package-lock.json
  package.json
Labels: documentation

#542 Removed inner padding from dnn-tab
  package.json
  src/components/dnn-tabs/dnn-tabs.scss
  src/components/dnn-tabs/dnn-tabs.stories.ts
Labels: enhancement

#544 Merged back latest fixes from 0.15.0 RC into develop
  .github/workflows/Publish_Site.yml
  .storybook/main.js
  .storybook/utilities.js
  _build/Build.cs
  licenses.txt
  package-lock.json
  package.json
  src/components/dnn-tabs/dnn-tabs.scss
  src/components/dnn-tabs/dnn-tabs.stories.ts
Labels: build
