Repository DNNCommunity/dnn-elements, pull requests merged in 2022-12, with the labels that each got.

#655 Fixed a few assets paths issues for monaco-editor
  licenses.json
  package-lock.json
  src/components.d.ts
  src/components/dnn-color-picker/readme.md
  src/components/dnn-image-cropper/readme.md
  src/components/dnn-monaco-editor/dnn-monaco-editor.scss
  src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  src/components/dnn-tab/readme.md
  stencil.config.ts
Labels: bug

#656 More monaco fixes
  custom-elements.json
  src/components/dnn-monaco-editor/dnn-monaco-editor.scss
  src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  src/components/dnn-monaco-editor/readme.md
  stencil.config.ts
Labels: bug

#658 Fixed class name for `dnn-monaco-editor`
  custom-elements.json
  licenses.json
  src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
Labels: bug

#659 Updates GitVersion
  _build/_build.csproj
Labels: dependencies

#660 Implemented loading `codicon.ttf` from CDN and local
  custom-elements.json
  src/components.d.ts
  src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  src/components/dnn-monaco-editor/readme.md
Labels: bug

#661 Releases v0.16.0
  .gitignore
  _build/_build.csproj
  custom-elements.json
  licenses.json
  licenses.txt
  package-lock.json
  package.json
  src/components.d.ts
  src/components/dnn-color-picker/readme.md
  src/components/dnn-image-cropper/readme.md
  src/components/dnn-monaco-editor/dnn-monaco-editor.scss
  src/components/dnn-monaco-editor/dnn-monaco-editor.stories.ts
  src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  src/components/dnn-monaco-editor/readme.md
  src/components/dnn-monaco-editor/utils/code.utils.ts
  src/components/dnn-tab/readme.md
  src/index.html
  stencil.config.ts
Labels: build

#662 Merge `release/0.16.0` into `develop` post v0.16.0 release
  _build/_build.csproj
  custom-elements.json
  licenses.json
  package-lock.json
  package.json
  src/components.d.ts
  src/components/dnn-color-picker/readme.md
  src/components/dnn-image-cropper/readme.md
  src/components/dnn-monaco-editor/dnn-monaco-editor.scss
  src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  src/components/dnn-monaco-editor/readme.md
  src/components/dnn-tab/readme.md
  stencil.config.ts
Labels: maintenance
