Repository DNNCommunity/dnn-elements, pull requests merged in 2022-09, with the labels that each got.

#579 Raised modal z-index
  src/components/dnn-modal/dnn-modal.scss
Labels: bug

#581 Bump Nuke from 6.0.1 to 6.2.1
  .nuke/build.schema.json
  _build/_build.csproj
  build.ps1
  build.sh
  global.json
  licenses.txt
  package-lock.json
  package.json
Labels: dependencies

#582 Pulls back Jest to v27
  package-lock.json
  package.json
Labels: dependencies

#606 Upgraded Storybook to v6.5.12
  .eslintrc.js
  package.json
  src/components.d.ts
Labels: dependencies

#607 Corrected plugin name typo
  .eslintrc.js
  licenses.txt
Labels: dependencies

#608 Updated develop with latest fixes on v0.15.1
  .eslintrc.js
  licenses.txt
  package.json
  src/components.d.ts
Labels: dependencies

#609 Released v0.15.1
  .eslintrc.js
  .nuke/build.schema.json
  _build/_build.csproj
  build.ps1
  build.sh
  global.json
  licenses.txt
  package-lock.json
  package.json
  src/components.d.ts
  src/components/dnn-modal/dnn-modal.scss
Labels: build

#610 Upgrade `lit-html` to v2.3.1
  package-lock.json
  package.json
Labels: bug
