Repository DNNCommunity/dnn-elements, pull requests merged in 2023-07, with the labels that each got.

#750 Dnn select doesn't update fix
  packages/stencil-library/src/components/dnn-select/dnn-select.tsx
Labels: bug

#756 Fixed an issue with input controls alignment
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
Labels: bug

#757 Merged `release/0.19.0` into `main` to release `v0.19.0`
  .nuke/build.schema.json
  _build/Build.cs
  _build/_build.csproj
  build.cmd
  build.ps1
  build.sh
  global.json
  package-lock.json
  packages/react-library/lib/components/stencil-generated/index.ts
  packages/react-library/package.json
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/package-lock.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-button/dnn-button.scss
  packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts
  packages/stencil-library/src/components/dnn-button/dnn-button.tsx
  packages/stencil-library/src/components/dnn-button/readme.md
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.tsx
  packages/stencil-library/src/components/dnn-dropzone/readme.md
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.stories.ts
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-input/dnn-input.stories.ts
  packages/stencil-library/src/components/dnn-input/dnn-input.tsx
  packages/stencil-library/src/components/dnn-input/readme.md
  packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.stories.ts
  packages/stencil-library/src/components/dnn-select/dnn-select.tsx
  packages/stencil-library/src/components/dnn-select/readme.md
  packages/stencil-library/src/components/dnn-tab/dnn-tab.stories.ts
  packages/stencil-library/src/components/dnn-tabs/dnn-tabs.stories.ts
  packages/stencil-library/src/index.html
  packages/stencil-library/vscode-data.json
Labels: build

#759 Fixed a console error when not using drag on dnn-modal
  packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
Labels: bug

#761 Merged `Hotfix/0.19.1` into `develop` for next release
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-button/dnn-button.scss
  packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts
  packages/stencil-library/src/components/dnn-button/dnn-button.tsx
  packages/stencil-library/src/components/dnn-button/readme.md
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.tsx
  packages/stencil-library/src/index.html
  packages/stencil-library/vscode-data.json
Labels: build

#765 Bumps Stencil to v4.0.1 as per migration guide
  package-lock.json
  packages/react-library/lib/components/stencil-generated/react-component-lib/utils/attachProps.ts
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/package.json
Labels: dependencies

#769 Improved dnn-image-cropper so it can work without a crop ratio too
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
  packages/stencil-library/src/index.html
Labels: bug

#770 Fixed an issue that caused console errors with dnn-select
  packages/stencil-library/src/components/dnn-select/dnn-select.tsx
Labels: bug

#771 Added a clear method to dnn-image-cropper
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
  packages/stencil-library/src/components/dnn-image-cropper/readme.md
Labels: enhancement

#772 Merged `release/0.20.0` into `main` to release `v0.20.0`
  package-lock.json
  packages/react-library/lib/components/stencil-generated/react-component-lib/utils/attachProps.ts
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/package-lock.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
  packages/stencil-library/src/components/dnn-image-cropper/readme.md
  packages/stencil-library/src/components/dnn-select/dnn-select.tsx
  packages/stencil-library/src/index.html
Labels: build
