Repository DNNCommunity/dnn-elements, pull requests merged in 2023-11, with the labels that each got.

#886 Ran storybook migration scripts
  package-lock.json
  packages/stencil-library/licenses.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
Labels: dependencies

#895 Configured Jest to use `new` headless mode
  packages/stencil-library/stencil.config.ts
Labels: dependencies

#896 Manually bumped jest to v29
  package-lock.json
  packages/stencil-library/package.json
Labels: dependencies

#899 Changed import for `create` on storybook theming
  packages/stencil-library/.storybook/manager.ts
Labels: dependencies

#901 Merged `release/0.22.0` fixes back into `develop` for next release
  packages/stencil-library/src/components/dnn-color-input/dnn-color-input.scss
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
  packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.tsx
Labels: bug

#902 Merged `release/0.23.0` into `main` to release `v0.23.0`
  package-lock.json
  package.json
  packages/stencil-library/.storybook/manager.ts
  packages/stencil-library/licenses.json
  packages/stencil-library/package-lock.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.tsx
  packages/stencil-library/src/components/dnn-dropzone/types.ts
  packages/stencil-library/src/index.html
  packages/stencil-library/stencil.config.ts
Labels: build

#905 Refine readme files for published npm packages a repo
  README.md
  packages/react-library/README.md
  packages/stencil-library/README.md
Labels: enhancement

#906 Released v0.23.1
  README.md
  packages/react-library/README.md
  packages/stencil-library/README.md
Labels: build
