Repository DNNCommunity/dnn-elements, pull requests merged in 2023-08, with the labels that each got.

#781 Dnn image cropper non-image files fix
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
Labels: bug

#783 Fixed an issue with label alignment of inputs
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
Labels: bug

#785 Merged `release/0.20.1` into `main` to release `v0.20.1`
  package-lock.json
  packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.scss
  packages/stencil-library/src/components/dnn-chevron/dnn-chevron.scss
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
  packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.scss
  packages/stencil-library/src/components/dnn-tabs/dnn-tabs.scss
Labels: build

#793 Bumped typescript to v5.0.4
  package-lock.json
  packages/stencil-library/package.json
Labels: dependencies

#786 Implemented dnn-richtext component
  package-lock.json
  packages/react-library/lib/components/stencil-generated/index.ts
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-monaco-editor/readme.md
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.scss
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.stories.ts
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
  packages/stencil-library/src/components/dnn-richtext/readme.md
  packages/stencil-library/src/index.html
  packages/stencil-library/src/utilities/stringUtilities.ts
  packages/stencil-library/tsconfig.json
  packages/stencil-library/vscode-data.json
Labels: enhancement

#794 Downgraded eslint to latest v7
  package-lock.json
  packages/stencil-library/package.json
Labels: dependencies

#800 Add progress bar component
  packages/react-library/lib/components/stencil-generated/index.ts
  packages/stencil-library/.storybook/preview-head.html
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-progress-bar/dnn-progress-bar.scss
  packages/stencil-library/src/components/dnn-progress-bar/dnn-progress-bar.stories.ts
  packages/stencil-library/src/components/dnn-progress-bar/dnn-progress-bar.tsx
  packages/stencil-library/src/components/dnn-progress-bar/readme.md
  packages/stencil-library/src/index.html
  packages/stencil-library/vscode-data.json
Labels: feature

#802 Added jodit/types to exports
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/index.ts
  packages/stencil-library/vscode-data.json
Labels: bug

#803 Attempting to inherit jodit config
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext-config.ts
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
  packages/stencil-library/src/components/dnn-richtext/readme.md
  packages/stencil-library/src/index.ts
Labels: bug

#804 Added node-polyfills
  package-lock.json
  packages/stencil-library/package.json
  packages/stencil-library/stencil.config.ts
Labels: bug

#805 Use tyeof instead of importing type
  packages/stencil-library/custom-elements.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext-config.ts
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
  packages/stencil-library/src/components/dnn-richtext/readme.md
Labels: bug

#806 Add-back Jodit
  packages/stencil-library/package.json
Labels: bug

#807 Made Jodit a hard dependency
  package-lock.json
  packages/stencil-library/package.json
Labels: bug

#808 export only config type from jodit
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
Labels: bug

#810 Fixed a sizing/positioning issue with dnn-select and dnn-input
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
Labels: bug

#811 Merged `release/0.20.2` into `main` to release `v0.20.2`
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
Labels: build

#812 Updated `develop` with latest fixes from `release/0.20.2`
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
Labels: bug

#813 Updated `release/0.21.0` with latest fixes from `release/0.20.2`
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
Labels: bug
