Repository DNNCommunity/dnn-elements, pull requests merged in 2023-04, with the labels that each got.

#681 Removed storybook
  .eslintrc.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/utilities.js
  custom-elements.json
  licenses.json
  package.json
  src/components/dnn-button/dnn-button.stories.ts
  src/components/dnn-checkbox/dnn-checkbox.stories.ts
  src/components/dnn-chevron/dnn-chevron.stories.ts
  src/components/dnn-collapsible/dnn-collapsible.stories.ts
  src/components/dnn-color-picker/dnn-color-picker.stories.ts
  src/components/dnn-dropzone/dnn-dropzone.stories.ts
  src/components/dnn-image-cropper/dnn-image-cropper.stories.ts
  src/components/dnn-modal/dnn-modal.stories.ts
  src/components/dnn-monaco-editor/dnn-monaco-editor.stories.ts
  src/components/dnn-permissions-grid/dnn-permissions-grid.stories.ts
  src/components/dnn-searchbox/dnn-searchbox.stories.ts
  src/components/dnn-sort-icon/dnn-sort-icon.stories.ts
  src/components/dnn-tab/dnn-tab.stories.ts
  src/components/dnn-tabs/dnn-tabs.stories.ts
  src/components/dnn-toggle/dnn-toggle.stories.ts
  src/components/dnn-treeview-item/dnn-treeview-item.stories.ts
  src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.stories.ts
  src/components/dnn-vertical-splitview/dnn-vertical-splitview.stories.ts
Labels: documentation

#684 Updated Nuke to v.6.3.0
  _build/Build.cs
  _build/_build.csproj
  global.json
  licenses.json
  package-lock.json
  package.json
Labels: dependencies

#691 Bumped stencil to v3.1.0
  licenses.json
  package-lock.json
  package.json
  src/components.d.ts
  stencil.config.ts
Labels: dependencies

#693 Started re-implementation of new storybook
  .eslintrc.js
  nx.json
  package-lock.json
  package.json
  packages/react-library/.storybook/main.ts
  packages/react-library/package.json
  packages/react-library/stories/Button.stories.ts
  packages/react-library/stories/Button.tsx
  packages/react-library/stories/DnnButton.stories.tsx
  packages/react-library/stories/Header.stories.ts
  packages/react-library/stories/Header.tsx
  packages/react-library/stories/Introduction.mdx
  packages/react-library/stories/Page.stories.ts
  packages/react-library/stories/Page.tsx
  packages/react-library/stories/assets/code-brackets.svg
  packages/react-library/stories/assets/colors.svg
  packages/react-library/stories/assets/comments.svg
  packages/react-library/stories/assets/direction.svg
  packages/react-library/stories/assets/flow.svg
  packages/react-library/stories/assets/plugin.svg
  packages/react-library/stories/assets/repo.svg
  packages/react-library/stories/assets/stackalt.svg
  packages/react-library/stories/button.css
  packages/react-library/stories/header.css
  packages/react-library/stories/page.css
  packages/stencil-library/.babelrc.json
  packages/stencil-library/.eslintrc.js
  packages/stencil-library/.storybook/main.ts
  packages/stencil-library/.storybook/manager.ts
  packages/stencil-library/.storybook/preview-head.html
  packages/stencil-library/.storybook/preview.ts
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts
  packages/stencil-library/stencil.config.ts
  packages/stencil-library/tsconfig.json
Labels: enhancement

#694 Resolve broken image for DNN logo in storybook
  packages/stencil-library/.storybook/assets/DNNLogo.svg
  packages/stencil-library/.storybook/main.ts
  packages/stencil-library/.storybook/manager.ts
  packages/stencil-library/custom-elements.json
  packages/stencil-library/vscode-data.json
Labels: bug

#695 Optimize `args` for `DnnButton`
  packages/stencil-library/package-lock.json
  packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts
Labels: enhancement

#696 Implemented notes replacement
  package-lock.json
  packages/stencil-library/.storybook/main.ts
  packages/stencil-library/.storybook/preview.ts
  packages/stencil-library/.storybook/preview.tsx
  packages/stencil-library/package.json
  packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts
Labels: enhancement

#697 Added accessibility to storybooks.
  package-lock.json
  packages/stencil-library/.storybook/main.ts
  packages/stencil-library/package.json
Labels: enhancement

#698 All new stories for DNN components.
  packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts
  packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.stories.ts
  packages/stencil-library/src/components/dnn-chevron/dnn-chevron.stories.ts
  packages/stencil-library/src/components/dnn-collapsible/dnn-collapsible.stories.ts
  packages/stencil-library/src/components/dnn-color-picker/dnn-color-picker.stories.ts
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.stories.ts
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.stories.ts
  packages/stencil-library/src/components/dnn-modal/dnn-modal.stories.ts
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.stories.ts
  packages/stencil-library/src/components/dnn-permissions-grid/dnn-permissions-grid.stories.ts
  packages/stencil-library/src/components/dnn-searchbox/dnn-searchbox.stories.ts
  packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.stories.ts
  packages/stencil-library/src/components/dnn-tab/dnn-tab.stories.ts
  packages/stencil-library/src/components/dnn-tabs/dnn-tabs.stories.ts
  packages/stencil-library/src/components/dnn-toggle/dnn-toggle.stories.ts
  packages/stencil-library/src/components/dnn-treeview-item/dnn-treeview-item.stories.ts
  packages/stencil-library/src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.stories.ts
  packages/stencil-library/src/components/dnn-vertical-splitview/dnn-vertical-splitview.stories.ts
Labels: documentation
