Repository DNNCommunity/dnn-elements, pull requests merged in 2023-05, with the labels that each got.

#706 Removed duplicate storybook and fixed some build issues
  _build/Build.cs
  package-lock.json
  packages/react-library/.storybook/main.ts
  packages/react-library/.storybook/preview.ts
  packages/react-library/package.json
  packages/react-library/stories/Button.stories.ts
  packages/react-library/stories/Button.tsx
  packages/react-library/stories/DnnButton.stories.tsx
  packages/react-library/stories/Header.stories.ts
  packages/react-library/stories/Header.tsx
  packages/react-library/stories/Introduction.mdx
  packages/react-library/stories/Page.stories.ts
  packages/react-library/stories/Page.tsx
  packages/react-library/stories/assets/code-brackets.svg
  packages/react-library/stories/assets/colors.svg
  packages/react-library/stories/assets/comments.svg
  packages/react-library/stories/assets/direction.svg
  packages/react-library/stories/assets/flow.svg
  packages/react-library/stories/assets/plugin.svg
  packages/react-library/stories/assets/repo.svg
  packages/react-library/stories/assets/stackalt.svg
  packages/react-library/stories/button.css
  packages/react-library/stories/header.css
  packages/react-library/stories/page.css
  packages/stencil-library/package.json
Labels: build

#707 Fixed yaml file for publishing site
  .github/workflows/Publish_Site.yml
Labels: build

#708 Changed Pulish_Site.yml to actually call Nuke target
  .github/workflows/Publish_Site.yml
Labels: build

#709 Fixed a typo in PublishSite.yml
  .github/workflows/Publish_Site.yml
Labels: build

#711 Merged latest fixes from v0.17.0 into `develop`
  .github/workflows/Publish_Site.yml
  _build/Build.cs
  packages/react-library/.storybook/main.ts
  packages/react-library/.storybook/preview.ts
  packages/react-library/package.json
  packages/react-library/stories/Button.stories.ts
  packages/react-library/stories/Button.tsx
  packages/react-library/stories/DnnButton.stories.tsx
  packages/react-library/stories/Header.stories.ts
  packages/react-library/stories/Header.tsx
  packages/react-library/stories/Introduction.mdx
  packages/react-library/stories/Page.stories.ts
  packages/react-library/stories/Page.tsx
  packages/react-library/stories/assets/code-brackets.svg
  packages/react-library/stories/assets/colors.svg
  packages/react-library/stories/assets/comments.svg
  packages/react-library/stories/assets/direction.svg
  packages/react-library/stories/assets/flow.svg
  packages/react-library/stories/assets/plugin.svg
  packages/react-library/stories/assets/repo.svg
  packages/react-library/stories/assets/stackalt.svg
  packages/react-library/stories/button.css
  packages/react-library/stories/header.css
  packages/react-library/stories/page.css
  packages/stencil-library/.storybook/manager.ts
  packages/stencil-library/package.json
Labels: build

#714 Removed rogue css import
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.scss
  packages/stencil-library/src/index.html
Labels: bug

#716 Released v0.17.1
  _build/Build.cs
  package-lock.json
  packages/react-library/package.json
  packages/stencil-library/.storybook/main.ts
  packages/stencil-library/.storybook/preview-head.html
  packages/stencil-library/.storybook/preview.tsx
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/package-lock.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.scss
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.stories.ts
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  packages/stencil-library/src/components/dnn-monaco-editor/readme.md
  packages/stencil-library/src/components/dnn-monaco-editor/types/options.ts
  packages/stencil-library/src/index.html
  packages/stencil-library/stencil.config.ts
  packages/stencil-library/vscode-data.json
Labels: build

#717 Merged latest fixes on v0.17.1 into develop
  _build/Build.cs
  package-lock.json
  packages/react-library/package.json
  packages/stencil-library/.storybook/main.ts
  packages/stencil-library/.storybook/preview-head.html
  packages/stencil-library/.storybook/preview.tsx
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/package-lock.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.scss
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.stories.ts
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  packages/stencil-library/src/components/dnn-monaco-editor/readme.md
  packages/stencil-library/src/components/dnn-monaco-editor/types/options.ts
  packages/stencil-library/src/index.html
  packages/stencil-library/stencil.config.ts
  packages/stencil-library/vscode-data.json
Labels: bug

#712 Changed order and colors of dnn-button modal
  packages/stencil-library/src/components/dnn-button/dnn-button.tsx
Labels: enhancement

#713 Makes dnn-Modal resizable.
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
  packages/stencil-library/src/components/dnn-modal/dnn-modal.scss
  packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
Labels: enhancement

#726 Made dnn-button disabled more disabled.
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-button/dnn-button.scss
  packages/stencil-library/src/components/dnn-button/dnn-button.tsx
Labels: enhancement

#729 added dnn-treeview story templates.
  packages/stencil-library/src/components/dnn-treeview-item/dnn-treeview-item.stories.ts
Labels: documentation

#727 Added a optional filesize limit for dnn-dropzone.
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.scss
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.stories.ts
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.tsx
  packages/stencil-library/src/components/dnn-dropzone/readme.md
  packages/stencil-library/src/components/dnn-dropzone/types.ts
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
  packages/stencil-library/src/components/dnn-image-cropper/readme.md
  packages/stencil-library/src/components/dnn-modal/readme.md
  packages/stencil-library/src/index.html
  packages/stencil-library/src/utilities/stringUtilities.ts
  packages/stencil-library/vscode-data.json
  tsconfig.json
Labels: enhancement

#730 Added vertical splitview for dnn-vertical-overflowmenu.
  packages/stencil-library/src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.stories.ts
Labels: bug

#731 Released v0.18.0
  package-lock.json
  packages/stencil-library/custom-elements.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-button/dnn-button.scss
  packages/stencil-library/src/components/dnn-button/dnn-button.tsx
  packages/stencil-library/src/components/dnn-collapsible/dnn-collapsible.stories.ts
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.scss
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.stories.ts
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.tsx
  packages/stencil-library/src/components/dnn-dropzone/readme.md
  packages/stencil-library/src/components/dnn-dropzone/types.ts
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
  packages/stencil-library/src/components/dnn-image-cropper/readme.md
  packages/stencil-library/src/components/dnn-modal/dnn-modal.scss
  packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
  packages/stencil-library/src/components/dnn-modal/readme.md
  packages/stencil-library/src/components/dnn-treeview-item/dnn-treeview-item.stories.ts
  packages/stencil-library/src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.stories.ts
  packages/stencil-library/src/index.html
  packages/stencil-library/src/utilities/stringUtilities.ts
  packages/stencil-library/vscode-data.json
  tsconfig.json
Labels: build

#732 Fixed Tabs and Tab story structure.
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components/dnn-tab/dnn-tab.stories.ts
  packages/stencil-library/src/components/dnn-tabs/dnn-tabs.stories.ts
Labels: documentation
