Repository DNNCommunity/dnn-elements, pull requests merged in 2024-03, with the labels that each got.

#971 Properly completed Nuke update to v8
  _build/_build.csproj
  build.ps1
  build.sh
  package-lock.json
  packages/react-library/package.json
  packages/stencil-library/licenses.json
  packages/stencil-library/package-lock.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components/dnn-input/readme.md
  packages/stencil-library/src/components/dnn-vertical-splitview/readme.md
Labels: dependencies

#993 Made dnn-richtext form aware
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.scss
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
  packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
Labels: enhancement

#998 Resolved issue with `--color-text` not applying to inactive tab text color
  packages/stencil-library/src/components/dnn-tabs/dnn-tabs.scss
Labels: bug

#996 Resolved typo in HTML example for dnn-tabs and added TSX example
  packages/stencil-library/src/components/dnn-tabs/readme.md
Labels: bug, enhancement

#1007 Implemented Usage documentation for dnn-tabs
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/src/components/dnn-richtext/readme.md
  packages/stencil-library/src/components/dnn-tabs/readme.md
  packages/stencil-library/src/components/dnn-tabs/usage/HTML.md
  packages/stencil-library/src/components/dnn-tabs/usage/JSX-TSX.md
  packages/stencil-library/src/components/examples/dnn-example-form/readme.md
  packages/stencil-library/vscode-data.json
Labels: enhancement

#1015 Implemented usage documentation for dnn-button
  packages/stencil-library/src/components/dnn-button/readme.md
  packages/stencil-library/src/components/dnn-button/usage/HTML.md
  packages/stencil-library/src/components/dnn-button/usage/JSX-TSX.md
Labels: enhancement

#1016 Migrated dnn-color-input and dnn-input in new dnn-fieldset
  packages/stencil-library/licenses.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-color-input/dnn-color-input.scss
  packages/stencil-library/src/components/dnn-color-input/dnn-color-input.tsx
  packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss
  packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.tsx
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-input/dnn-input.tsx
  packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
  packages/stencil-library/src/index.html
Labels: enhancement

#1017 Updated dnn-select to use dnn-fieldset
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-color-input/readme.md
  packages/stencil-library/src/components/dnn-fieldset/readme.md
  packages/stencil-library/src/components/dnn-input/readme.md
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
  packages/stencil-library/src/components/dnn-select/dnn-select.tsx
  packages/stencil-library/src/components/dnn-select/readme.md
  packages/stencil-library/src/components/examples/dnn-example-form/readme.md
  packages/stencil-library/vscode-data.json
Labels: enhancement

#1019 Improved validation support of dnn-select
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-select/dnn-select.tsx
  packages/stencil-library/src/components/dnn-select/readme.md
  packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
Labels: enhancement

#1020 Implemented dnn-textarea input field
  packages/react-library/lib/components/stencil-generated/index.ts
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss
  packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.tsx
  packages/stencil-library/src/components/dnn-fieldset/readme.md
  packages/stencil-library/src/components/dnn-input/dnn-input.tsx
  packages/stencil-library/src/components/dnn-textarea/dnn-textarea.scss
  packages/stencil-library/src/components/dnn-textarea/dnn-textarea.stories.ts
  packages/stencil-library/src/components/dnn-textarea/dnn-textarea.tsx
  packages/stencil-library/src/components/dnn-textarea/readme.md
  packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
  packages/stencil-library/src/components/examples/dnn-example-form/readme.md
  packages/stencil-library/vscode-data.json
Labels: enhancement
