Repository DNNCommunity/dnn-elements, pull requests merged in 2024-07, with the labels that each got.

#1090 Update security URL
  CONTRIBUTING.md
Labels: maintenance

#1091 Implemented `Usage` documentation for `dnn-sort-icon`
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/src/components/dnn-sort-icon/readme.md
  packages/stencil-library/src/components/dnn-sort-icon/usage/HTML.md
  packages/stencil-library/src/components/dnn-sort-icon/usage/JSX-TSX.md
  packages/stencil-library/vscode-data.json
Labels: enhancement

#1093 Updated to utilize `focus-visible` styles instead of `focus`
  packages/stencil-library/src/components/dnn-button/dnn-button.scss
  packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.scss
  packages/stencil-library/src/components/dnn-chevron/dnn-chevron.scss
  packages/stencil-library/src/components/dnn-modal/dnn-modal.scss
  packages/stencil-library/src/components/dnn-searchbox/dnn-searchbox.scss
  packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.scss
  packages/stencil-library/src/components/dnn-tabs/dnn-tabs.scss
  packages/stencil-library/src/components/dnn-toggle/dnn-toggle.scss
Labels: enhancement

#1096 Fixed an issue that caused too few large bundles
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/stencil.config.ts
  packages/stencil-library/vscode-data.json
Labels: bug

#1116 Added `focus` and `blur` logic to `dnn-autocomplete`
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx
  packages/stencil-library/src/components/dnn-autocomplete/readme.md
Labels: enhancement

#1121 Re-organized bundles
  packages/stencil-library/stencil.config.ts
Labels: enhancement

#1122 Fixed an issue that caused label to overlay prefix/suffix
  packages/stencil-library/src/components/dnn-input/dnn-input.tsx
Labels: bug

#1119 Added programmatic support to focus or blur elements
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx
  packages/stencil-library/src/components/dnn-autocomplete/readme.md
  packages/stencil-library/src/components/dnn-button/dnn-button.tsx
  packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.tsx
  packages/stencil-library/src/components/dnn-chevron/dnn-chevron.scss
  packages/stencil-library/src/components/dnn-chevron/dnn-chevron.tsx
  packages/stencil-library/src/components/dnn-color-input/dnn-color-input.tsx
  packages/stencil-library/src/components/dnn-color-picker/dnn-color-picker.tsx
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.tsx
  packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
  packages/stencil-library/src/components/dnn-input/dnn-input.tsx
  packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
  packages/stencil-library/src/components/dnn-permissions-grid/dnn-permissions-grid.tsx
  packages/stencil-library/src/components/dnn-permissions-grid/localization-interface.ts
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
  packages/stencil-library/src/components/dnn-searchbox/dnn-searchbox.tsx
  packages/stencil-library/src/components/dnn-select/dnn-select.tsx
  packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.tsx
  packages/stencil-library/src/components/dnn-textarea/dnn-textarea.tsx
  packages/stencil-library/src/components/dnn-toggle/dnn-toggle.tsx
  packages/stencil-library/src/components/dnn-treeview-item/dnn-treeview-item.tsx
  packages/stencil-library/src/index.html
Labels: enhancement

#1123 Fixed an invalid debounce property
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-searchbox/dnn-searchbox.tsx
  packages/stencil-library/src/components/dnn-searchbox/readme.md
  packages/stencil-library/src/index.html
  packages/stencil-library/src/utilities/debounce.ts
  packages/stencil-library/vscode-data.json
Labels: bug
