Repository DNNCommunity/dnn-elements, pull requests merged in 2025-01, with the labels that each got.

#1245 Released v0.25.0
  packages/stencil-library/custom-elements.json
  packages/stencil-library/package.json
  packages/stencil-library/src/components.d.ts
  packages/stencil-library/src/components/dnn-button/readme.md
  packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.tsx
  packages/stencil-library/src/components/dnn-checkbox/readme.md
  packages/stencil-library/src/components/dnn-permissions-grid/dnn-permissions-grid.tsx
  packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
  packages/stencil-library/src/components/dnn-richtext/readme.md
  packages/stencil-library/src/components/dnn-select/readme.md
  packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
  packages/stencil-library/vscode-data.json
Labels: build

#1247 Updated border and background color for `dnn-dropzone` for compatibility with DNN 10
  package-lock.json
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.scss
  packages/stencil-library/vscode-data.json
Labels: enhancement

#1250 Released v0.25.1
  package-lock.json
  packages/stencil-library/custom-elements.json
  packages/stencil-library/licenses.json
  packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.scss
  packages/stencil-library/src/index.html
  packages/stencil-library/vscode-data.json
Labels: build

#1252 Fixed some issues with css-variables of inputs
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.scss
  packages/stencil-library/src/components/dnn-color-input/dnn-color-input.scss
  packages/stencil-library/src/components/dnn-color-input/readme.md
  packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss
  packages/stencil-library/src/components/dnn-fieldset/readme.md
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-input/readme.md
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
  packages/stencil-library/src/components/dnn-select/readme.md
  packages/stencil-library/src/components/dnn-textarea/dnn-textarea.scss
  packages/stencil-library/src/components/dnn-textarea/readme.md
Labels: bug

#1253 Released v0.26.0
  packages/stencil-library/custom-elements.json
  packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.scss
  packages/stencil-library/src/components/dnn-color-input/dnn-color-input.scss
  packages/stencil-library/src/components/dnn-color-input/readme.md
  packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss
  packages/stencil-library/src/components/dnn-fieldset/readme.md
  packages/stencil-library/src/components/dnn-input/dnn-input.scss
  packages/stencil-library/src/components/dnn-input/readme.md
  packages/stencil-library/src/components/dnn-select/dnn-select.scss
  packages/stencil-library/src/components/dnn-select/readme.md
  packages/stencil-library/src/components/dnn-textarea/dnn-textarea.scss
  packages/stencil-library/src/components/dnn-textarea/readme.md
Labels: build
